### ISSUE TITLE
Upload Function Stopped Working

### ISSUE THREAD

**Issue by sqrboy** [henkelmax/camera#47] opened 2022-07-07 07:49 UTC
Hi, the upload function has always worked for me, but suddenly the upload button no longer opens Finder for me to upload images. I click on it and nothing happens, all of the other buttons in the Camera work fine - have you come across this before?

**Comment by henkelmax** [comment] 2022-07-07 07:50
Please fill out the bug template.

**Comment by sqrboy** [comment] 2022-07-07 08:13
**Bug description**
Hi, the upload function has always worked for me, but suddenly the upload button no longer opens Finder for me to upload images. I click on it and nothing happens, all of the other buttons in the Camera work fine - have you come across this before?

**Steps to reproduce the issue**
1. Go to 'Camera'
2. Click on 'Upload Button'
3. No error displayed, Finder just doesn't open to allow me to upload images.

**Expected behavior**
I expected a Finder window to open for me to upload images.

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete.
You can use [https://gist.github.com/](https://gist.github.com/).
[2022-07-07-5.log](https://github.com/henkelmax/camera/files/9061654/2022-07-07-5.log)

**Versions**
- 1.18.2
- 40.1.54 (MC 1.18.2)
- 1.0.4
- 
**Other mods**
Only WorldEdit 7.2.10 was installed, I tried with this removed and the issue still remains.

**Screenshots (Optional)**
N/A

**Comment by henkelmax** [comment] 2022-07-07 08:48
This seems to be a macos issue. I am not able to test that, since I don't own a mac.

**Comment by henkelmax** [comment] 2022-07-07 09:55
Alright, I can confirm this is a MacOS only issue. That will be a wontfix, sorry.

**Closed by henkelmax** 2022-07-07 09:55 UTC
Labels: bug
